"""
CMake & Make compilation database (compile_commands.json) parser.

Extracts:
- Source files (.c / .cpp) from compile_commands.json generated by CMake
  (`cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON`) or Make (`bear -- make`,
  `compiledb make`, `intercept-build make`).
- Per-file include paths (-I, -isystem, -iquote, /I)
- Per-file preprocessor defines (-D, /D)
- Compiler working directories for relative path resolution

Produces a `CompileCommandsParseResult` compatible with `EWPParseResult`
for seamless consumption by `fwlens.parser.pipeline.run_pipeline`.
"""

from __future__ import annotations

import json
import os
import shlex
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from fwlens.config import FwLensConfig
from fwlens.model.project import BoundaryClass, IARGroup
from fwlens.parser.ewp import TranslationUnit, _classify_boundary


@dataclass
class CompileCommandsParseResult:
    source_files: list[TranslationUnit]
    iar_groups: dict[str, IARGroup]
    global_defines: list[str]
    global_includes: list[Path]
    configuration_name: str


def parse_compiler_flags(cmd_str_or_args: str | list[str], base_dir: Path) -> tuple[list[str], list[Path]]:
    """
    Parse compiler command string or arguments list to extract defines and include paths.
    """
    if isinstance(cmd_str_or_args, str):
        try:
            tokens = shlex.split(cmd_str_or_args, posix=os.name != 'nt')
        except Exception:
            tokens = cmd_str_or_args.split()
    else:
        tokens = list(cmd_str_or_args)

    defines: list[str] = []
    includes: list[Path] = []

    idx = 0
    while idx < len(tokens):
        tok = tokens[idx]

        # Defines: -DNAME, -DNAME=VAL, /DNAME, /DNAME=VAL
        if tok in ("-D", "/D"):
            if idx + 1 < len(tokens):
                idx += 1
                defines.append(tokens[idx])
        elif tok.startswith("-D") or tok.startswith("/D"):
            val = tok[2:]
            if val:
                defines.append(val)
        # Includes: -Ipath, -I path, -isystem path, -iquote path, /Ipath, /I path
        elif tok in ("-I", "-isystem", "-iquote", "/I"):
            if idx + 1 < len(tokens):
                idx += 1
                p_str = tokens[idx]
                p = Path(p_str) if Path(p_str).is_absolute() else (base_dir / p_str).resolve()
                includes.append(p)
        elif tok.startswith("-I") or tok.startswith("/I"):
            p_str = tok[2:]
            if p_str:
                p = Path(p_str) if Path(p_str).is_absolute() else (base_dir / p_str).resolve()
                includes.append(p)
        elif tok.startswith("-isystem") or tok.startswith("-iquote"):
            prefix_len = 8
            p_str = tok[prefix_len:]
            if p_str:
                p = Path(p_str) if Path(p_str).is_absolute() else (base_dir / p_str).resolve()
                includes.append(p)

        idx += 1

    return defines, includes


def extract_clang_flags(cmd_str_or_args: str | list[str], base_dir: Path) -> list[str]:
    """
    Pick out the compiler flags that change how a file must be parsed -- language
    standard, target, machine options and forced includes -- so they can be handed to
    clang instead of a hard-coded target (issue #48).
    """
    if isinstance(cmd_str_or_args, str):
        try:
            tokens = shlex.split(cmd_str_or_args, posix=os.name != 'nt')
        except Exception:
            tokens = cmd_str_or_args.split()
    else:
        tokens = list(cmd_str_or_args)

    out: list[str] = []
    idx = 0
    while idx < len(tokens):
        tok = tokens[idx]
        if tok.startswith("-std=") or tok.startswith("--target=") or tok.startswith("-m"):
            out.append(tok)
        elif tok in ("-target", "--target") and idx + 1 < len(tokens):
            out.append(f"--target={tokens[idx + 1]}")
            idx += 1
        elif tok == "-include" and idx + 1 < len(tokens):
            idx += 1
            p = Path(tokens[idx])
            out.extend(["-include", str(p if p.is_absolute() else (base_dir / p).resolve())])
        idx += 1
    return out


def find_compile_commands_json(config: FwLensConfig) -> Path:
    """
    Locate compile_commands.json based on config or common build directory conventions.
    """
    if config.project.compile_commands and config.project.compile_commands.exists():
        return config.project.compile_commands

    search_dirs = [
        config.project.proj_dir,
        config.project.proj_dir / "build",
        config.project.proj_dir / "build" / "Debug",
        config.project.proj_dir / "build" / "Release",
        Path.cwd(),
        Path.cwd() / "build",
    ]

    for d in search_dirs:
        candidate = d / "compile_commands.json"
        if candidate.exists():
            return candidate

    raise FileNotFoundError(
        "compile_commands.json not found. "
        "Specify `project.compile_commands` in config.yaml, or ensure CMake "
        "was run with `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON`, or generate it for "
        "Make using `bear -- make` or `compiledb make`."
    )


def parse_compile_commands(config: FwLensConfig) -> CompileCommandsParseResult:
    """
    Parse compile_commands.json and return translation units and metadata.
    """
    json_path = find_compile_commands_json(config)

    with open(json_path, encoding="utf-8") as f:
        entries = json.load(f)

    translation_units: list[TranslationUnit] = []
    global_defines_set: set[str] = set(config.iar_compat_defines)
    global_includes_set: set[Path] = set()

    groups: dict[str, IARGroup] = {}

    for entry in entries:
        file_raw = entry.get("file")
        if not file_raw:
            continue

        work_dir = Path(entry.get("directory", str(config.project.proj_dir)))
        file_path = Path(file_raw)
        if not file_path.is_absolute():
            file_path = (work_dir / file_path).resolve()

        if file_path.suffix.lower() not in (".c", ".cpp", ".cc", ".cxx"):
            continue

        cmd_args = entry.get("arguments") or entry.get("command", "")
        file_defines, file_includes = parse_compiler_flags(cmd_args, work_dir)
        file_clang_flags = extract_clang_flags(cmd_args, work_dir)

        # Merge config compat defines
        all_file_defines = list(config.iar_compat_defines)
        seen_defs = {d.split("=")[0] for d in all_file_defines}
        for d in file_defines:
            k = d.split("=")[0]
            if k not in seen_defs:
                all_file_defines.append(d)
                seen_defs.add(k)

        global_defines_set.update(file_defines)
        global_includes_set.update(file_includes)

        boundary = _classify_boundary(file_path, config)

        # Create directory-based group name if available
        try:
            rel_group = str(file_path.relative_to(config.project.proj_dir).parent).replace("\\", "/")
        except ValueError:
            rel_group = file_path.parent.name

        if rel_group and rel_group != "." and rel_group not in groups:
            groups[rel_group] = IARGroup(name=rel_group, parent=None)

        if rel_group and rel_group != ".":
            groups[rel_group].files.append(file_path)

        tu = TranslationUnit(
            path=file_path,
            defines=all_file_defines,
            include_paths=file_includes,
            boundary_class=boundary,
            iar_group=rel_group if rel_group != "." else None,
            extra_args=file_clang_flags,
        )
        translation_units.append(tu)

    # Deduplicate translation units by path
    seen: set[Path] = set()
    unique_tus = []
    for tu in translation_units:
        if tu.path not in seen:
            seen.add(tu.path)
            unique_tus.append(tu)

    mode_name = config.project.mode if config.project.mode in ("cmake", "make", "compile_commands") else "compile-commands"

    return CompileCommandsParseResult(
        source_files=unique_tus,
        iar_groups=groups,
        global_defines=list(global_defines_set),
        global_includes=list(global_includes_set),
        configuration_name=f"{mode_name} ({json_path.name})",
    )
